### ISSUE TITLE
Crashing during startup after updating to v4.10

### ISSUE THREAD

**Issue by jtfen86** [dqx-translation-project/dqxclarity#190]
Here's my startup.log file's contents.

```
**********************
Windows PowerShell transcript start
Start time: 20240403000642
Username: JFPC1\jtfen
RunAs User: JFPC1\jtfen
Configuration Name: 
Machine: JFPC1 (Microsoft Windows NT 10.0.22635.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted & D:\dqxclarity\run_clarity.ps1
Process ID: 14012
PSVersion: 5.1.22621.2706
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2706
BuildVersion: 10.0.22621.2706
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is logs/startup.log
Creating virtual environment.

Installing dqxclarity dependencies.


Python install location: C:\Program Files (x86)\Python311-32\python.exe
Clarity installation path: D:\dqxclarity
Clarity flags: -pndlcc
Running dqxclarity.
2024-04-03 00:07:00.966 | INFO     | __main__:blast_off:57 - Getting started. DO NOT TOUCH THE GAME OR REMOVE YOUR MEMOR
Y CARD.
2024-04-03 00:07:00.967 | INFO     | __main__:blast_off:59 - Ensuring db structure.
2024-04-03 00:07:01.866 | INFO     | __main__:blast_off:65 - Updating DAT mod.
2024-04-03 00:07:17.080 | SUCCESS  | common.update:download_dat_files:324 - DQX path verified.
2024-04-03 00:07:17.082 | INFO     | common.update:download_dat_files:341 - Downloading DAT1 and IDX files.
2024-04-03 00:07:19.371 | SUCCESS  | common.update:download_dat_files:351 - Translation files downloaded.
2024-04-03 00:07:19.374 | INFO     | __main__:blast_off:68 - Updating custom text in db.
2024-04-03 00:07:19.374 | INFO     | common.update:check_for_updates:112 - Checking dqxclarity repo for updates...
2024-04-03 00:07:19.810 | SUCCESS  | common.update:check_for_updates:132 - Clarity is up to date! (Current version: 4.10
.0)
2024-04-03 00:07:19.812 | INFO     | common.update:download_custom_files:33 - Downloading custom translation files from
dqx-translation-project/dqx-custom-translations.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\dqxclarity\main.py", line 104, in <module>
    blast_off()
  File "D:\dqxclarity\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dqxclarity\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\dqxclarity\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dqxclarity\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dqxclarity\main.py", line 70, in blast_off
    download_custom_files()
  File "D:\dqxclarity\common\update.py", line 62, in download_custom_files
    read_glossary_and_import(data)
  File "D:\dqxclarity\common\update.py", line 253, in read_glossary_and_import
    ja, en = record.split(",", 1)
    ^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
PS>$global:?
True
**********************
Windows PowerShell transcript end
End time: 20240403000721
**********************

```

**Comment by jmctune** [comment]
Sorry for the delay. I guess I am not getting email notifications when issues are being opened on this account. I'll get that fixed.

Is this issue still occurring? I'm aware there was an invalid value in the glossary that's downloaded that's since been fixed. If you have updates enabled, it should download the new glossary with the fixed values. Let me know, thanks.

**Comment by jtfen86** [comment]
It didn't happen again when I tried it after noticing your post, must have been because it failed to download something. I haven't been playing actually so I forgot I even made this issue.
